version: '3.8'

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
      - VITE_BASE_URL=${BASE_URL}
      - VITE_API_URL=${API_URL}
    depends_on:
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/letsencrypt:/etc/letsencrypt"

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - SECURITY_JWT_SECRET=${SECURITY_JWT_SECRET}
      - SECURITY_JWT_EXPIRATION=${SECURITY_JWT_EXPIRATION}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
