version: "3.7"
services:
  db:
    image: postgres
    restart: always
    ports:
      - "15432:5432"
    environment:
      - "POSTGRES_USER=admin"
      - "POSTGRES_PASSWORD=admin"
      - "POSTGRES_DB=greenify-db"