name: Tests and checks

on:
  push: 
    branches: [ master ]
    paths: [ '**.java', '.github/workflows/build.yml', 'pom.xml' ]
  pull_request:
    branches: [ master ]

jobs:
  frontend:
    name: Compile the frontend
    runs-on: ubuntu-latest
    env:
      working-directory: ./client
    defaults:
      run:
        working-directory: ${{ env.working-directory }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Perform a clean install
        run: npm ci
      - name: Build and compile the project
        run: npm run build --if-present

  backend:
    name: Compile and test the backend
    runs-on: ubuntu-latest
    env:
      working-directory: ./server
    defaults:
      run:
        working-directory: ${{ env.working-directory }}
    permissions: read-all
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.6
      - name: Build backend
        run: mvn -B verify -D spring.profiles.active=ci pitest:mutationCoverage
      - name: Extract pull request number
        uses: jwalton/gh-find-current-pr@v1
        id: pr
      - name: Run Quality Monitor
        uses: uhafner/quality-monitor@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pr-number: ${{ steps.pr.outputs.number }}
