name: CI/CD Pipeline

on:
  push:
    branches: 
      - master
  # pull_request:
  #   branches: 
  #     - master

jobs:
  build-frontend:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install dependencies
      run: npm install
    - name: Build frontend
      run: npm run build
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: frontend
        path: dist/
  build-backend:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B verify -D spring.profiles.active=ci pitest:mutationCoverage
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: backend
        path: target/
    - name: Upload test reports
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.REPOSITORY_NAME }}-reports
        path: |
          target/site/jacoco/
          target/pit-reports/
  deploy-frontend:
    needs: build-frontend
    runs-on: ubuntu-latest

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: frontend
    - name: Set environment variable
      run: echo "APP_NAME=$(if [ "${{ github.event_name }}" = "pull_request" ]; then echo 'greenify-client-staging'; else echo 'greenify-client-production'; fi)" >> $GITHUB_ENV    
    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.APP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }} # TODO: deze vastleggen in env
        package: .
  deploy-backend:
    needs: build-backend
    runs-on: ubuntu-latest

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: backend
    - name: Set environment variable
      run: echo "APP_NAME=$(if [ "${{ github.event_name }}" = "pull_request" ]; then echo 'greenify-client-staging'; else echo 'greenify-client-production'; fi)" >> $GITHUB_ENV    
    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.APP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }} # TODO: deze vastleggen in env
        package: .